app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path:     /{_locale}
    defaults: { _controller: AppBundle:Default:index, _locale: es}

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix :  /{_locale}/

app_crud:
    resource: "@AppBundle/Resources/config/routing.yml"
